#!/bin/bash

#SBATCH --nodes=2
#SBATCH --ntasks=26
#SBATCH --partition=development
#SBATCH --time=02:00:00
#SBATCH --job-name=MQD

# Parameters to be set manually
iterations=10
rundir=/home/jchoi157/lustre/amr

#execname="$1 $2 $3 $4 $5 $6"
#logname=`echo $execname | cut -d " " -f 1`

execname="$1"
max_depth=4
num_iters=1
lb_freq=3

logdir=`pwd`
rm -rf $logfile
rm -rf $resultfile

cd $rundir

for array_dim in 512
do
  for block_size in 64
  do
    outfile="$execname-$block_size-$array_dim.out"
    logfile="$execname-$block_size-$array_dim.log"
    resultfile="$execname-$block_size-$array_dim.result"

    runstr="Running $execname $max_depth $block_size $num_iters $lb_freq $array_dim"
    echo $runstr
    echo $runstr >> "$logdir/$resultfile"

    for pVal in 1 2 4 8 16 23
    do
      echo "Using $pVal PEs"
      runtime_acc=0.0
      errortime_acc=0.0
      for (( iteration=1; iteration<=$iterations; iteration++ ))
      do
        echo "Iteration $iteration"

        ./charmrun +p$pVal ++ppn $pVal ++local $execname $max_depth $block_size $num_iters $lb_freq $array_dim > $logdir/$outfile

        runtime=`grep -i "simulation time" $logdir/$outfile | cut -d ":" -f 2 | cut -d " " -f 2`
        errortime=`grep -i "average time" $logdir/$outfile | cut -d ":" -f 2 | cut -d " " -f 2`
        echo "+p $pVal $runtime $errortime" >> $logdir/$logfile
        runtime_acc=$(echo "$runtime_acc + $runtime" | bc)
        errortime_acc=$(echo "$errortime_acc + $errortime" | bc)
      done
      runtime_avg=$(echo "scale=6; $runtime_acc / $iterations" | bc)
      errortime_avg=$(echo "scale=6; $errortime_acc / $iterations" | bc)
      echo "[$pVal PEs] average execution time: $runtime_avg, average local error calculation time: $errortime_avg" >> "$logdir/$resultfile"
    done
  done
done
